# Modify id to your specific user id
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY2NjliMjNiMmYxYzEzOWM5NmVmY2Y0ZiIsImlhdCI6MTcxODIwNDYyOH0.FnIBF0Vba8UPqZEYPyoxLLPVReoyNAAo6kil5MOeyVQ

{
  "title": "test",
  "author": "test",
  "url": "test",
  "likes": 0,
  "user": "6669b23b2f1c139c96efcf4f"
}
